import {
  Megaphone,
  Scale,
  HeartPulse,
  Brain,
  Baby,
  ShieldPlus,
  Leaf,
  HandHeart,
  Route,
  Users2,
  GraduationCap,
  HeartHandshake,
  Accessibility,
  ShieldAlert,
  Coins,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  megaphone: Megaphone,
  scale: Scale,
  "heart-pulse": HeartPulse,
  brain: Brain,
  baby: Baby,
  "shield-plus": ShieldPlus,
  leaf: Leaf,
  "hand-heart": HandHeart,
  route: Route,
  Users2: Users2,
  GraduationCap: GraduationCap,
  HeartHandshake: HeartHandshake,
  Accessibility: Accessibility,
  ShieldAlert: ShieldAlert,
  Coins: Coins,
  // Kebab case fallbacks
  "users-2": Users2,
  "graduation-cap": GraduationCap,
  "heart-handshake": HeartHandshake,
  accessibility: Accessibility,
  "shield-alert": ShieldAlert,
  coins: Coins,
};
